<a href="https://colab.research.google.com/github/TanzimaShaikh/MLP/blob/main/day2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#hstack
print("Hello Tanzima")

Hello Tanzima


In [2]:
import numpy as np
a=np.array([1,2,3])
b=np.array([5,6,7])

In [3]:
a

array([1, 2, 3])

In [4]:
b

array([5, 6, 7])

In [5]:
c=np.hstack((a,b))
c

array([1, 2, 3, 5, 6, 7])

In [6]:
d=np.vstack((a,b))
d

array([[1, 2, 3],
       [5, 6, 7]])

In [7]:

#arange
e=np.arange(1,11)
e

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
f=np.arange(2,21,2)
f

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [9]:
g=np.linspace(1.0,5.0,num=10)

In [10]:
g

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [11]:
h=np.linspace(1.0,10.0,20)
h

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [12]:
i=np.array([[1,2,3],[4,5,6]])
i

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
j=np.array([[7,8,9],[10,11,12]])
j

array([[ 7,  8,  9],
       [10, 11, 12]])

In [16]:
hs=np.hstack((i,j))

In [17]:
hs

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [18]:
vs=np.stack((i,j))
vs

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [19]:
t=np.arange(13,131,13) #table of 13
t

array([ 13,  26,  39,  52,  65,  78,  91, 104, 117, 130])

In [20]:
#indexing and slicing
s=np.array([[7,8,9],[10,11,12]])
s.size

6

In [26]:
s.shape

(2, 3)

In [24]:
s[0:1]    #slicing aceessing 1st element/row in 2d array

array([[7, 8, 9]])

In [25]:
s[1:2]    #2nd row

array([[10, 11, 12]])

In [27]:
s[0]

array([7, 8, 9])

In [28]:
s[1]

array([10, 11, 12])

In [33]:
s[0][0]

7

In [36]:
s[1][2]

12

In [37]:
s[:,2]

array([ 9, 12])

In [41]:
one=np.ones((4,4))
one

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [42]:
eye=np.eye(4)
eye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [48]:
rand=np.random.randint(0,10,size=(3,2))
rand


array([[2, 9],
       [2, 4],
       [0, 6]])

In [49]:
arr=np.array([1,2,3,4,5])
arr += 5
arr

array([ 6,  7,  8,  9, 10])

In [54]:
arr2=np.random.randint(1,10,size=(3,3))
arr2


array([[3, 9, 4],
       [5, 9, 8],
       [3, 9, 8]])

In [56]:
print(arr2.min())

3


In [57]:
print(arr2.max())

9


In [58]:
arr3=np.random.randint(1,10,size=(3,3))
print(arr3)

[[3 6 3]
 [1 4 4]
 [1 2 4]]


In [60]:
arr3=arr3.reshape(9,1)
print(arr3)

[[3]
 [6]
 [3]
 [1]
 [4]
 [4]
 [1]
 [2]
 [4]]


In [61]:
arr4=np.random.randint(1,10,size=(3,3))
print(arr4)
arr5=np.random.randint(1,10,size=(3,3))
print(arr5)

[[4 7 8]
 [6 3 7]
 [9 4 7]]
[[2 9 1]
 [2 4 4]
 [1 2 5]]


In [63]:
arrsum=np.add(arr4,arr5)
arrsum

array([[ 6, 16,  9],
       [ 8,  7, 11],
       [10,  6, 12]])

In [65]:
ze=np.zeros((5,2))
ze

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [67]:
on=np.ones((3,3))
on

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [73]:
td=np.array([[1,2],[3,4]])
td

array([[1, 2],
       [3, 4]])

In [74]:
td=td.T  #swap rows and columns
print(td)

[[1 3]
 [2 4]]
